2025-03-01 21:05:25,837 [DEBUG] Processing transaction date: 2024-12-17, type: <class 'datetime.date'>
2025-03-01 21:05:25,837 [ERROR] Date parsing error: isinstance() arg 2 must be a type or tuple of types
2025-03-01 21:05:25,838 [ERROR] Traceback (most recent call last):
  File "c:\Users\alexander.bennett\PycharmProjects\PlaidApp\ASB_personal_finance_app\app.py", line 365, in get_transactions
    elif isinstance(tx_date_str, datetime.date):
TypeError: isinstance() arg 2 must be a type or tuple of types

2025-03-01 21:05:25,838 [DEBUG] Processing transaction date: 2024-12-16, type: <class 'datetime.date'>
2025-03-01 21:05:25,838 [ERROR] Date parsing error: isinstance() arg 2 must be a type or tuple of types
2025-03-01 21:05:25,838 [ERROR] Traceback (most recent call last):
  File "c:\Users\alexander.bennett\PycharmProjects\PlaidApp\ASB_personal_finance_app\app.py", line 365, in get_transactions
    elif isinstance(tx_date_str, datetime.date):
TypeError: isinstance() arg 2 must be a type or tuple of types

2025-03-01 21:05:25,839 [DEBUG] Processing transaction date: 2024-12-15, type: <class 'datetime.date'>
2025-03-01 21:05:25,839 [ERROR] Date parsing error: isinstance() arg 2 must be a type or tuple of types
2025-03-01 21:05:25,839 [ERROR] Traceback (most recent call last):
  File "c:\Users\alexander.bennett\PycharmProjects\PlaidApp\ASB_personal_finance_app\app.py", line 365, in get_transactions
    elif isinstance(tx_date_str, datetime.date):
TypeError: isinstance() arg 2 must be a type or tuple of types

2025-03-01 21:05:25,839 [DEBUG] Processing transaction date: 2024-12-05, type: <class 'datetime.date'>
2025-03-01 21:05:25,839 [ERROR] Date parsing error: isinstance() arg 2 must be a type or tuple of types
2025-03-01 21:05:25,840 [ERROR] Traceback (most recent call last):
  File "c:\Users\alexander.bennett\PycharmProjects\PlaidApp\ASB_personal_finance_app\app.py", line 365, in get_transactions
    elif isinstance(tx_date_str, datetime.date):
TypeError: isinstance() arg 2 must be a type or tuple of types

2025-03-01 21:05:25,840 [DEBUG] Processing transaction date: 2024-12-03, type: <class 'datetime.date'>
2025-03-01 21:05:25,840 [ERROR] Date parsing error: isinstance() arg 2 must be a type or tuple of types
2025-03-01 21:05:25,840 [ERROR] Traceback (most recent call last):
  File "c:\Users\alexander.bennett\PycharmProjects\PlaidApp\ASB_personal_finance_app\app.py", line 365, in get_transactions
    elif isinstance(tx_date_str, datetime.date):
TypeError: isinstance() arg 2 must be a type or tuple of types

2025-03-01 21:05:25,842 [INFO] Total transactions after processing: 45
2025-03-01 21:05:25,842 [INFO] === Transaction Retrieval Complete ===
2025-03-01 21:05:25,842 [INFO] 127.0.0.1 - - [01/Mar/2025 21:05:25] "GET /get_transactions HTTP/1.1" 200 -
2025-03-01 21:07:07,129 [INFO]  * Detected change in 'c:\\Users\\alexander.bennett\\PycharmProjects\\PlaidApp\\ASB_personal_finance_app\\app.py', reloading
2025-03-01 21:07:07,129 [INFO]  * Detected change in 'c:\\Users\\alexander.bennett\\PycharmProjects\\PlaidApp\\ASB_personal_finance_app\\app.py', reloading
2025-03-01 21:07:07,152 [INFO]  * Detected change in 'c:\\Users\\alexander.bennett\\PycharmProjects\\PlaidApp\\ASB_personal_finance_app\\app.py', reloading
2025-03-01 21:07:07,773 [INFO]  * Restarting with watchdog (windowsapi)
